### ISSUE TITLE
Rename resolve method

### ISSUE THREAD

**Issue by keshaldesai** [FDC3/API#36]
The `resolve` method for the `DesktopAgent` interface is generically named. I propose that it be renamed to `queryIntents`, `queryActions`, `findIntents`, `findActions`, or something similar.

**Comment by ColinEberhardt** [comment]
That's a very good suggestion. Resolve is equally confusing because of the relationship it has to `Promise.resolve`, and the Desktop-Agents 'resolver'.

I like method / function names that are simple and descriptive. I'd vote for your `findIntents` suggestion.

(query tends to suggest a more complex interaction involving filters / criteria etc ...)

**Comment by rikoe** [comment]
I concur. The fact that `raiseIntent` returns an `IntentResolution` type is also confusing when contrasted with the `resolve` method.

**Comment by nkolba** [comment]
_findIntents_ sounds good to me.  I will make a PR.

**Comment by rikoe** [comment]
@ColinEberhardt the only issue I see with `findIntents` is that the return type is  `ActionMetadata` so that is slightly inconsistent, but I don't think it is a big deal.
