### ISSUE TITLE
fdc3.register how is the app name determined?

### ISSUE THREAD

**Issue by ColinEberhardt** [FDC3/API#4]
[fdc3.register](https://github.com/FDC3/API/blob/master/Specification-Draft.MD#42-register) id documented as follows:
> Dynamically registers an intent with the agent. Returns confirmation of the registration.
>
> `fdc3.register(intent: String)`

However, the documentation for resolve indicates that an intent / context pair resolves to a list of app names.

When you register an intent via `fdc3.register` how is the app name determined?

**Comment by nkolba** [comment]
App name would either be known to the Desktop Agent (because it launched the App) - or a provisional name would be assigned by the Desktop Agent.  

I punted on the context arg.  Can add it in.  Still need to define a syntax for an App to register the context types it accepts (for a specific intent).

**Comment by nkolba** [comment]
Closing, as we have removed register from the spec.
