### ISSUE TITLE
Suggestion: Better docs around this API and the context/intent repos

### ISSUE THREAD

**Issue by bschwinn** [FDC3/API#8]
Perhaps just starting with a README approach, where we link the repo docs together.  Followed with some Typescript defs for contexts and intents we can reference here.

**Comment by rikoe** [comment]
Let's make sure this is done.

Instead of `type Context = Object;`, there should be a shared TypeScript definition of a context object with the [Context Data](https://github.com/FDC3/ContextData) repo.

Where an intent object is returned as a result of a lookup, it should share a TypeScript definition with the [Intents](https://github.com/FDC3/Intents) repo, ideally matching [Intent.yaml](https://github.com/FDC3/Intents/blob/master/src/Intent.yaml).

Where an application, or application metadata, is referenced, it should link to the [App Directory](https://github.com/FDC3/App-Directory) repo, and ideally match [appd.yaml]( https://github.com/FDC3/appd-api/blob/master/specification/appd.yaml).

**Comment by nkolba** [comment]
Will be reflected in v1 documentation
